### ISSUE TITLE
[master] Database should support "as" for selecting columns.

### ISSUE THREAD

**Issue by marktopper** [fistlab/php#3]
I am still unsure how the syntax for this should be.

So I'm open for ideas.

**EDIT:** Example query `SELECT username as name FROM users`
Currently it is not possible to make `as` in selections of columns.

Currently you can select specific columns by using this code:

```
$db->table('users')->select('username', 'email')->get();
```

I was thinking about doing as-selecting like this but then the system would have problem supporting some cases of tables where columns include spaces.

```
$db->table('users')->select('username as name', 'email')->get();
```

**Comment by acekyd** [comment]
Please add a readme to the project and of course more insight into the issue

**Comment by 3onyc** [comment]
Yup, what're the components, example of the issue, etc.

**Comment by marktopper** [comment]
Readme coming right up.

**Comment by marktopper** [comment]
Readme.md have now been made.

**Comment by marktopper** [comment]
Maybe the best way to implement this method would be like this:

```
$db->table('users')->select(['column', 'alias'], 'email')->get();
```

That could use generate the sql

```
SELECT `column` as `alias`, `email` FROM `users`
```

**Comment by bennychan** [comment]
Just submitted a pull request for this.. Was trying to run the select in your original post and it was giving me an error: `$db->table('users')->select('username', 'email')->get();
`

I assume that it should have been `$db->table('users')->select(['username', 'email'])->get();` ?

For the commit, the method of using "as" in the select can be done by:

`$db->table('users')->select([ ['username', 'name], 'email' ])->get();`

**Comment by marktopper** [comment]
Thanks @bennychan.

// closed
